### ISSUE TITLE
building the beast ..

### ISSUE THREAD

**Issue by gedw99** [mlctrez/goapp-natsws#1]
Hey @mlctrez 

very cool stuff. I also use nats. 

any chance you can tell me what this is in https://github.com/mlctrez/goapp-natsws/blob/master/internal/go.mod#L6

replace github.com/maxence-charriere/go-app/v9 => ../../go-app 

Wondering what repo that is :)

I am building an open science project and the wasm nats stuff is really useful for it.

let me know if you have any questions.

**Comment by mlctrez** [comment]
Hey @gedw99 

I was tinkering with some changes to [go-app](github.com/maxence-charriere/go-app) to test  handling cases where a nil pointer is passed into app.Observer(..).Value().  The go-app repo is cloned in the same directory as the goapp-natws repo.

I'll remove it and touch up the Readme with steps on how to build the demo app.

Hope that helps.

**Comment by mlctrez** [comment]
@gedw99   

FYI, here's [another example](https://github.com/mlctrez/go-nats-app) that uses goapp-natsws.   

It uses an embedded nats server, which I think you were interested in.

**Comment by gedw99** [comment]
Thanks for helping out. 
the way your system hangs together is really impressive stuff.

I will have a look at those links and try thinks out.

I am planning to try both Embedded  Nats Server and NOT Embedded actually.

Why both ?
It maybe that Embedded can act as a Leaf Nats Server on their Desktops / Lab Server , federated with a Global Nats Server / Cluster in the cloud. So then 1,000 of scientists can run their own Embedded nats, but communicate globally via the Global Nats Server / Cluster.

**Comment by gedw99** [comment]
Oh btw I did work out what the import overrides you’re using is. It works on my side too.

**Comment by mlctrez** [comment]
Cleaning up some issues on my projects, I noticed this was still open.. closing now
